root: /
permalink: /:year-:month/:title/
markdown: kramdown

paginate: 4
paginate_path: '/page:num'

gems:
  - jekyll-archives
  - jekyll-paginate

exclude:
  - README.md

title: think in DevRel
author: DAMADAMA
email: "zoomquiet+devrel@gmail.com"



