root: /
permalink: /:year-:month/:title/
markdown: kramdown

paginate: 1
paginate_path: '/page:num'

gems:
  - jekyll-archives
  - jekyll-paginate

exclude:
  - README.md

title: think in RevRel
author: DRM4KN
email: "support@devrel.info"

